### ISSUE TITLE
[front-end] Adjust front-end project scaffolding

### ISSUE THREAD

**Issue by clh97** [clh97/heaven-and-hell#3]
**details:**
Add scaffolding so developers can easily integrate new screens and components

**todo:**
* [ ] Add react-router
* [ ] Add styled-components
* [ ] Create screens boilerplate
* [ ] Create components boilerplate
* [ ] Add example screen and component
* [ ]
